outofmemory db "Out of memory",0
filenotfound db "Source file not found",0
illegalchar db "Illegal Char '",0
syntaxerrorexpected db "Expected ", 0
syntaxerrortoken db "Token cannot appear after previous token",0
iwfnotallowed db "if, while, and for are not allowed here",0
unimplementednode db "Encountered unimplemented node type: ",0
unimplementedop db "Encountered unimplemented operator",0
varprefix db "Variable '",0
vardefined db "' is already defined",0
varnotdefined db "' is not defined",0
locnotreg db "Given location is not a register",0
locnotmem db "Given location is not a memory address",0
bugincom db "This is probably a bug in the compiler",0